### PR TITLE
Componentize cabot_serial_node + cabot_handle_v2 and combine them into one process .

### PR DESCRIPTION
**Pull request by yamahatayukiya**
As the title suggests, zero copy processing has also been implemented .
However, cabot_serial_node has an open issue that prevents it from peforming zero copies processing .

### CODE REVIEW

**Comment by daisukes** [comment]
I found some issues with the PR
- [x] cabot_serial_node makes two different nodes (CabotArduinoSerial should not be a Node)
- [x] pushed_X topics can be removed
- [ ] the node cannot be terminated when the port is not available

**Comment by daisukes** [comment]
@yamahatayukiya
Could you please test the code with ACE hardware again?

**Review by daisukes — APPROVED** [review]
Code works well. I made some chagnes.

**Comment by yamahatayukiya** [comment]
@dsato80 

Thank you for fix .
I built cabot-driver again on Ace1 and confirmed its operation .
Topic output and handle operations worked correctly .

**Pull request merged**
